fint:
  database:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  adapter:
    id: https://vigoiks.no/fintlabs-no/personvern/samtykke-henrik
    base-url: http://localhost:8081
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      samtykke:
        domain-name: personvern
        packageName: samtykke
        resource-name: samtykke
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
      behandling:
        domain-name: personvern
        packageName: samtykke
        resource-name: behandling
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
      tjeneste:
        domain-name: personvern
        packageName: samtykke
        resource-name: tjeneste
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
