security:
  basic:
    enabled: false

fint:
  metamodell: https://beta.felleskomponent.no/fint/metamodell/klasse
  adapter:
    organizations: mock.no
    status-endpoint: http://localhost:8080/provider/status
    response-endpoint: http://localhost:8080/provider/response

  oauth:
    enabled: false
