fint:
  adapter:
    id: https://vigoiks.no/fintlabs-no/personvern/samtykke
    base-url: https://alpha.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      samtykke:
        domain-name: personvern
        packageName: samtykke
        resource-name: samtykke
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      behandling:
        domain-name: personvern
        packageName: samtykke
        resource-name: behandling
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      tjeneste:
        domain-name: personvern
        packageName: samtykke
        resource-name: tjeneste
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE

spring:
  profiles:
    include:
      - db
      - oauth