server:
  port: 8091

springfox:
  title: '@title@'
  version: '@version@'

fint:
  metamodell: https://beta.felleskomponent.no/fint/metamodell/klasse
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
    organizations: fintlabs.no

  oauth:
    enabled: false
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client


spring:
  datasource:
    hikari:
      schema: fintlabs_no
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/fint-personvern-adapter
    username: postgres
    password: password
  jpa:
    properties:
      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: __init.sql
#              create-source: metadata
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      driver-class-name: org.postgresql.Driver
    flyway:
      locations: classpath:db/migration/