fint:
  adapter:
    id: https://vigoiks.no/fintlabs-no/personvern/samtykke-henrik
    password:
    username:
#    base-url: http://localhost:8081
    base-url: https://beta.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      samtykke:
        domain-name: personvern
        packageName: samtykke
        resource-name: samtykke
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
      behandling:
        domain-name: personvern
        packageName: samtykke
        resource-name: behandling
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
      tjeneste:
        domain-name: personvern
        packageName: samtykke
        resource-name: tjeneste
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter openid

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    hikari:
      schema: personvern_adapter
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300
