fint:
  metamodell: https://beta.felleskomponent.no/fint/metamodell/klasse
  adapter:
    id: https://vigoiks.no/fintlabs-no/personvern/samtykke
    password:
    username:
    #base-url: http://localhost:8081
    base-url: https://alpha.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      samtykke:
        domain-name: personvern
        packageName: samtykke
        resource-name: samtykke
        fullSyncIntervalInDays: 7

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter
  datasource:
    hikari:
      schema: fintlabs_no
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/fint_personvern_adapter
    username: postgres
    password: password
  jpa:
    properties:
      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: __init.sql
#              create-source: metadata
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    datasource:
      driver-class-name: org.postgresql.Driver
    flyway:
      locations: classpath:db/migration/