apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-personvern-adapter
  app.kubernetes.io/instance: fint-personvern-adapter_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: adapter
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-personvern-adapter_fintlabs_no"
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/env/2/value"
        value: "fintlabs.no"
    target:
      kind: Application
      name: fint-personvern-adapter

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-personvern-adapter_fintlabs_no"
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
    target:
      kind: FintAdapter
      name: personvern-adapter-credentials

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-personvern-adapter_fintlabs_no"
      - op: replace
        path: "/metadata/labels/fintlabs.no~1org-id"
        value: "fintlabs.no"
    target:
      kind: PGUser
      name: fint-personvern-adapter-pg