apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-personvern-adapter
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-personvern-adapter
    app.kubernetes.io/instance: fint-personvern-adapter_orgDash
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: orgDot
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: orgDot
  image: ghcr.io/fintlabs/fint-personvern-adapter:sha-0000000
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx512M'
    - name: fint.adapter.base-url
      value: 'https://beta.felleskomponent.no'
    - name: fint.adapter.org-id
      value: 'orgDot'
    - name: fint.adapter.id
      value: https://vigoiks.no/fintlabs-no/personvern/samtykke
  envFrom:
    - secretRef:
        name: personvern-adapter-credentials
    - secretRef:
         name: fint-personvern-adapter-pg
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }